<?php

    require_once("actions/db_connect.php");

    $display_journey = "";

    if(@$_GET["id"]){
    $id = $_GET["id"];

    $sql = "SELECT * FROM journeys WHERE journey_id = '{$id}';";
    $query = mysqli_query($connect, $sql);
    $record = mysqli_fetch_assoc($query);

    if(mysqli_num_rows($query) == 1){
        $location_name = $record["location_name"];
        $latitude = $record["latitude"];
        $longitude = $record["longitude"];

        $display_journey = "
            <div class='card bg-dark m-0' style='width: 100%; max-width: 720px; backdrop-filter: blur(500px)'>
            <div class='card-body text-light' style='backdrop-filter: blur(50px)'>
                <p class='card-title text-center display-4 mb-2'>{$record["location_name"]}</p>
                <hr class='mt-1 mb-2'>
                <p class='card-subtitle text-center mb-3 h6 text-warning'><i class='bi bi-geo-fill'></i> {$record["city"]} | {$record["country"]}</p>

                <p class='card-text mb-0'>
                <i class='bi bi-calendar-event fs-4 pe-2'></i> {$record["date"]}
                </p>
                <p class='card-text my-0'>
                <i class='bi bi-hourglass-split fs-4 pe-2'></i></i> {$record["duration"]} day(s)
                </p>
                <p class='card-text text-light mt-0'>
                <i class='bi bi-wallet2 fs-4'></i> <i class='bi bi-currency-euro'></i>{$record["price"]}
                </p>
                <p class='card-text mb-5'>
                <i class='bi bi-info-square fs-4 pe-2'></i> {$record["description"]}
                </p>
                
                <hr class='bg-success mt-2 mb-0 mx-5'>

                <p class='card-text text-center'><a id='link' class='text-decoration-none' href='index.php'><small><span id='arrow'> << </span>Return to main page</small></a></p>
            </div>
            <img src='img/{$record["picture"]}' class='img-fluid' alt='img/{$record["location_name"]}'>
            </div>
            ";
        }
    }
    

?>


<!-- 
------------------
    -- HTML --
------------------ 
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP -->
    <?php require_once("components/bootstrap.php"); ?>
    <style>
        #details{
            margin: 0px;
            padding: 5% 0% 3%;
            background: url("img/layout/hero.jpg") no-repeat bottom left;
            background-size: cover;
        }
    
        /* Google Maps style*/
        #map{
              height: 20vh;
              border-radius: 5px;
              border: whitesmoke 2px inset;
              box-sizing: border-box;
            }
        html, body, main {
            height: auto;
            margin: 0;
            padding: 0;
            /* background: yellow; */
        }

        #link{
            color: seagreen;
            transition: 0.45s;
        }
        a#link :hover{
            color: whitesmoke;
        }
    </style>
    <title>CR-12: Mount Everest</title>
</head>
<body>

    <!-- HERO & NAVBAR-->
    <?php 
        $hero = $url = "";
        require_once("components/hero.php");
        require_once("components/navbar.php"); 
        ?>

    <!-- MAIN -->
    <main id="details">
        
        <section class="row py-5" >
            <div class="col col-sm-12 offset-sm-0 col-md-5 offset-md-1" style='width: 100%; max-width: 720px; backdrop-filter: blur(1px)'>
                <!-- Google Maps -->
                <div class="my-1" id='map'></div>
                
                <!-- Generated Card via PHP -->
                <div id="card" class="w-100 my-1" style='width: 100%; max-width: 720px; backdrop-filter: blur(100px)'>
                    <?php echo $display_journey; ?>
                </div>
            </div>
        </section>

    </main>

    <!-- FOOTER -->
    <?php require_once("components/footer.php")?>
        
    <!-- Google Maps API Script -->
    <script>
            var map;
            function initMap() {
                //insert saved values previously generated by PHP as the name of the JS variable as well as its coordinates (lat and lng)
                var selected_location = {
                    lat: <?= $latitude ?>,
                    lng: <?= $longitude ?>
                };
                
                map = new google.maps.Map(document.getElementById('map'), {
                center: selected_location, 
                zoom: 5
                });
                var pinpoint = new google.maps.Marker({
                    position: selected_location,
                    map: map
                });
            }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBtjaD-saUZQ47PbxigOg25cvuO6_SuX3M&callback=initMap" async defer></script>
</body>
</html>