-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Erstellungszeit: 10. Jan 2022 um 13:05
-- Server-Version: 10.4.21-MariaDB
-- PHP-Version: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `fswd14_cr12_mount_everest_henry_ngosytchev`
--
CREATE DATABASE IF NOT EXISTS `fswd14_cr12_mount_everest_henry_ngosytchev` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `fswd14_cr12_mount_everest_henry_ngosytchev`;

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `journeys`
--

CREATE TABLE `journeys` (
  `journey_id` int(11) NOT NULL,
  `location_name` varchar(100) NOT NULL,
  `city` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `date` date DEFAULT NULL,
  `duration` tinyint(4) DEFAULT NULL,
  `price` float DEFAULT NULL,
  `latitude` decimal(10,8) NOT NULL,
  `longitude` decimal(11,8) NOT NULL,
  `picture` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Daten für Tabelle `journeys`
--

INSERT INTO `journeys` (`journey_id`, `location_name`, `city`, `country`, `description`, `date`, `duration`, `price`, `latitude`, `longitude`, `picture`) VALUES
(1, 'Gum', 'Moscow', 'Russia', 'Visit the fammous Shopping Centre opposite the Kremlin.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2021-12-31', 1, 54.99, '55.75496000', '37.62148000', 'moscow.jpg'),
(2, 'Taj Mahal', 'Agra', 'India', 'The Indian poet Rabindranath Tagore called the Taj Mahal a \"teardrop on the cheek of time.\" It remains a testament to the grief—and power—of an emperor.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2022-03-15', 1, 199.99, '27.18125000', '78.04155000', 'agra.jpg'),
(3, 'Quitinday Green Hills', 'Camalig', 'Phillipines', 'Leave far away into the forest of green mountains: loe yourself, find your balance, recharge your energy in a 2-days retreat.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2022-10-01', 2, 209.95, '13.10478000', '123.61765000', 'camalig_phillipines.jpg'),
(4, 'Cloud Gate', 'Chicago', 'USA', 'The Cradle of modern architecture', '2021-12-03', 5, 550, '41.89987000', '-87.62350000', 'chicago_usa.jpg'),
(5, 'Ta Phin Cave', 'Lao Cai', 'Vietnam', 'Rice Terraces\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Sed eos sit illo aut adipisci enim accusamus dolorem ut voluptatem quae officiis, excepturi repudiandae maxime, incidunt, minus alias quas doloremque sapiente!\nObcaecati, architecto nihil, labore sunt eveniet magnam nulla doloremque unde illum magni, officiis exercitationem maiores expedita delectus numquam id laudantium commodi amet! Officiis accusantium dolor velit veritatis impedit dolores! Aliquam.\nNam cupiditate ab laboriosam sint praesentium, iste libero doloremque iure expedita quod facilis obcaecati reprehenderit mollitia repellendus qui corporis, odio explicabo ea nemo assumenda hic corrupti deleniti! Necessitatibus, nostrum vel?', '2022-05-29', 2, 313.15, '22.40307000', '103.83675000', 'lao_cai.jpg'),
(6, 'Burj Khalifa', 'Dubai', 'Arab Emirates', 'Skyline view with million and one lights of the Arab Peninsula offered to you', '2021-12-21', 2, 240.5, '25.20705000', '55.27400000', 'dubai.jpg'),
(7, 'Somewhere in the Air', 'Windhoek', 'Namibia', 'Start of the airial 1 week long Journey through Africa takes place in the National Parc of Etosha, in the direction of the Meditteranean Sea.\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Sed eos sit illo aut adipisci enim accusamus dolorem ut voluptatem quae officiis, excepturi repudiandae maxime, incidunt, minus alias quas doloremque sapiente!\nObcaecati, architecto nihil, labore sunt eveniet magnam nulla doloremque unde illum magni, officiis exercitationem maiores expedita delectus numquam id laudantium commodi amet! Officiis accusantium dolor velit veritatis impedit dolores! Aliquam.\nNam cupiditate ab laboriosam sint praesentium, iste libero doloremque iure expedita quod facilis obcaecati reprehenderit mollitia repellendus qui corporis, odio explicabo ea nemo assumenda hic corrupti deleniti! Necessitatibus, nostrum vel?', '2022-02-21', 7, 825.35, '-18.88160000', '16.37683000', 'free_flight.jpg'),
(8, 'Somewhere on the Water', 'Patillas', 'Porto Rico', 'Let yourself flow by the current during a 3 days immersion in the Agean Sea.\nThe starting point is in Patillas.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2022-06-25', 3, 195.25, '17.97639000', '-65.99582000', 'free_float.jpg'),
(9, 'Somewhere in the Nature', 'Oymiakon', 'Russia', 'The most northern inhabited city in the world\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2022-07-17', 3, 235, '63.46391000', '142.77337000', 'free_nature.jpg'),
(10, 'Somewhere in the Run', 'Sahand', 'Iran', 'Unleash your inner freedom and let yourself dive into a 4 days adventure through the wild mountains of Sahand.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2020-08-15', 4, 320.5, '38.31048000', '46.40830000', 'free_run.jpg'),
(11, 'Somewhere in the Road', 'Albuquerque', 'USA', 'Start your ride towards the West coast through the desert from Albuquerque.', '2022-06-02', 4, 385, '35.14135000', '-106.65257000', 'free_ride.jpg'),
(12, 'Machu Picchu', 'Aguas Calientes', 'Peru', 'The heart of the Inca civilisation of the 15th century opens its doors for you.', '2021-09-21', 2, 276.65, '-13.16311000', '-72.54496000', 'peru.jpg'),
(13, 'Mykerinos Pyramid', 'Al Haram', 'Egypt', 'A glince into the past of the mighty Egypt rulers.', '2022-01-10', 1, 134.99, '29.97456000', '31.12822000', 'pyramid.jpg'),
(14, 'Wuyou Temple', 'Leshan', 'China', 'Bouddhisme has also deep roots in China. Leshan, offers you the possibility to discover the history of Buddhism in Sichuan.', '2021-12-19', 2, 164.99, '29.52851000', '103.77749000', 'leshan_china.jpg'),
(15, 'Mont Saint-Michel', 'Le Mont-Saint-Michel', 'France', 'Chef d\'oevre of the French architecture amidst the Manche Sea.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2022-05-25', 1, 89.95, '48.63610000', '-1.51162000', 'mont_saint_michel.jpg'),
(16, 'Hobbiton', 'Matamata', 'New Zealand', 'The House of Hobbits opens its doors ust for you. Revisit the epic places of the world famous Lord of the Rings saga.\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Sed eos sit illo aut adipisci enim accusamus dolorem ut voluptatem quae officiis, excepturi repudiandae maxime, incidunt, minus alias quas doloremque sapiente!\nObcaecati, architecto nihil, labore sunt eveniet magnam nulla doloremque unde illum magni, officiis exercitationem maiores expedita delectus numquam id laudantium commodi amet! Officiis accusantium dolor velit veritatis impedit dolores! Aliquam.\nNam cupiditate ab laboriosam sint praesentium, iste libero doloremque iure expedita quod facilis obcaecati reprehenderit mollitia repellendus qui corporis, odio explicabo ea nemo assumenda hic corrupti deleniti! Necessitatibus, nostrum vel?', '2022-08-01', 2, 295, '-37.86642000', '175.68331000', 'kondor_new_zealand.jpg'),
(17, 'Charyn', 'Tamerlik', 'Khazakhstan', 'Kazakhstan is wide and variious in its geology. Charyn Kanyon is one of many natural wonders the country has to offer.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2022-04-26', 1, 69.99, '43.35747000', '79.07737000', 'kanyon_kz.jpg'),
(18, 'Minato City', 'Tokyo', 'Japan', 'Sake, sake, sake... Night life in Tokyo is not less lively as in New York City. \nAny doubts? Join us, and see for youself.\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2021-11-30', 1, 129.99, '35.66518000', '139.73392000', 'tokyo.jpg'),
(19, 'Kazakh Steppe', 'Ilyisk', 'Kazakhstan', 'Ride on a back of a horse through endless Kazakh Steppe\n\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam eveniet eligendi earum inventore soluta, similique porro atque, modi rem distinctio magnam asperiores fugiat officia dolores odit fugit. Perspiciatis, id harum.\nVoluptatibus impedit aspernatur quos, aliquam ea soluta, maxime iste repellendus aperiam, sequi maiores alias corrupti veniam atque officia? Voluptatum, fuga? Similique, consequatur a quam blanditiis sunt ex voluptatem accusamus dolorum.\nMaxime tempore, fugiat eveniet fuga recusandae explicabo. Odit reiciendis esse error nobis obcaecati, voluptate est. Velit voluptatem, ducimus quidem molestias vero recusandae et molestiae incidunt accusantium, ad, fugit a tenetur!\nAccusamus maxime eum quibusdam, tenetur vel corporis ut nulla quam sit ea. Quisquam corrupti sed dolores mollitia fuga in quae, quidem debitis nemo ea sit quibusdam commodi impedit placeat eos.', '2022-06-16', 2, 170, '44.07321000', '76.99841000', 'steppe_kz.jpg'),
(20, 'Nairobi Heritage Tours', 'Nairobi', 'Kenia', 'African Continent is booming. Nairobi is an ideal destination to start the discovery of the continent from the East.\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Sed eos sit illo aut adipisci enim accusamus dolorem ut voluptatem quae officiis, excepturi repudiandae maxime, incidunt, minus alias quas doloremque sapiente!\nObcaecati, architecto nihil, labore sunt eveniet magnam nulla doloremque unde illum magni, officiis exercitationem maiores expedita delectus numquam id laudantium commodi amet! Officiis accusantium dolor velit veritatis impedit dolores! Aliquam.\nNam cupiditate ab laboriosam sint praesentium, iste libero doloremque iure expedita quod facilis obcaecati reprehenderit mollitia repellendus qui corporis, odio explicabo ea nemo assumenda hic corrupti deleniti! Necessitatibus, nostrum vel?', '2022-02-06', 4, 320, '-1.28119000', '36.82403000', 'nairobi.jpg'),
(21, 'Mont Fuji', 'Nagawa', 'Japan', 'Admire the Japanese Megapolice from the Sky.\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Sed eos sit illo aut adipisci enim accusamus dolorem ut voluptatem quae officiis, excepturi repudiandae maxime, incidunt, minus alias quas doloremque sapiente!\nObcaecati, architecto nihil, labore sunt eveniet magnam nulla doloremque unde illum magni, officiis exercitationem maiores expedita delectus numquam id laudantium commodi amet! Officiis accusantium dolor velit veritatis impedit dolores! Aliquam.\nNam cupiditate ab laboriosam sint praesentium, iste libero doloremque iure expedita quod facilis obcaecati reprehenderit mollitia repellendus qui corporis, odio explicabo ea nemo assumenda hic corrupti deleniti! Necessitatibus, nostrum vel?', '2021-12-26', 1, 195, '35.36268000', '138.72703000', 'nagawa.jpg'),
(22, 'Place de la Bourse ', 'Bordeaux', 'France', 'Magnificent French architechture from the 18th century.\n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Sed eos sit illo aut adipisci enim accusamus dolorem ut voluptatem quae officiis, excepturi repudiandae maxime, incidunt, minus alias quas doloremque sapiente!\nObcaecati, architecto nihil, labore sunt eveniet magnam nulla doloremque unde illum magni, officiis exercitationem maiores expedita delectus numquam id laudantium commodi amet! Officiis accusantium dolor velit veritatis impedit dolores! Aliquam.\nNam cupiditate ab laboriosam sint praesentium, iste libero doloremque iure expedita quod facilis obcaecati reprehenderit mollitia repellendus qui corporis, odio explicabo ea nemo assumenda hic corrupti deleniti! Necessitatibus, nostrum vel?', '2022-01-26', 1, 105, '44.84163000', '-0.57010000', 'bordeaux.jpg');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `journeys`
--
ALTER TABLE `journeys`
  ADD PRIMARY KEY (`journey_id`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `journeys`
--
ALTER TABLE `journeys`
  MODIFY `journey_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=145;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
